// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: crea/ms-users/v1/users.proto

package users

import (
	fmt "fmt"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	proto "google.golang.org/protobuf/proto"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Users service

func NewUsersEndpoints() []*api.Endpoint {
	return []*api.Endpoint{
		{
			Name:    "Users.Create",
			Path:    []string{"/v1/users"},
			Method:  []string{"POST"},
			Handler: "rpc",
		},
		{
			Name:    "Users.Get",
			Path:    []string{"/v1/users/{user_id}"},
			Method:  []string{"GET"},
			Handler: "rpc",
		},
		{
			Name:    "Users.Mutate",
			Path:    []string{"/v1/users/{user_id}"},
			Method:  []string{"PUT"},
			Handler: "rpc",
		},
		{
			Name:    "Users.Delete",
			Path:    []string{"/v1/users/{user_id}"},
			Method:  []string{"DELETE"},
			Handler: "rpc",
		},
	}
}

// Client API for Users service

type UsersService interface {
	Create(ctx context.Context, in *User, opts ...client.CallOption) (*User, error)
	Get(ctx context.Context, in *GetUserRequest, opts ...client.CallOption) (*User, error)
	Mutate(ctx context.Context, in *User, opts ...client.CallOption) (*User, error)
	Delete(ctx context.Context, in *DeleteUserRequest, opts ...client.CallOption) (*emptypb.Empty, error)
}

type usersService struct {
	c    client.Client
	name string
}

func NewUsersService(name string, c client.Client) UsersService {
	return &usersService{
		c:    c,
		name: name,
	}
}

func (c *usersService) Create(ctx context.Context, in *User, opts ...client.CallOption) (*User, error) {
	req := c.c.NewRequest(c.name, "Users.Create", in)
	out := new(User)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersService) Get(ctx context.Context, in *GetUserRequest, opts ...client.CallOption) (*User, error) {
	req := c.c.NewRequest(c.name, "Users.Get", in)
	out := new(User)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersService) Mutate(ctx context.Context, in *User, opts ...client.CallOption) (*User, error) {
	req := c.c.NewRequest(c.name, "Users.Mutate", in)
	out := new(User)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersService) Delete(ctx context.Context, in *DeleteUserRequest, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "Users.Delete", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Users service

type UsersHandler interface {
	Create(context.Context, *User, *User) error
	Get(context.Context, *GetUserRequest, *User) error
	Mutate(context.Context, *User, *User) error
	Delete(context.Context, *DeleteUserRequest, *emptypb.Empty) error
}

func RegisterUsersHandler(s server.Server, hdlr UsersHandler, opts ...server.HandlerOption) error {
	type users interface {
		Create(ctx context.Context, in *User, out *User) error
		Get(ctx context.Context, in *GetUserRequest, out *User) error
		Mutate(ctx context.Context, in *User, out *User) error
		Delete(ctx context.Context, in *DeleteUserRequest, out *emptypb.Empty) error
	}
	type Users struct {
		users
	}
	h := &usersHandler{hdlr}
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "Users.Create",
		Path:    []string{"/v1/users"},
		Method:  []string{"POST"},
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "Users.Get",
		Path:    []string{"/v1/users/{user_id}"},
		Method:  []string{"GET"},
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "Users.Mutate",
		Path:    []string{"/v1/users/{user_id}"},
		Method:  []string{"PUT"},
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "Users.Delete",
		Path:    []string{"/v1/users/{user_id}"},
		Method:  []string{"DELETE"},
		Handler: "rpc",
	}))
	return s.Handle(s.NewHandler(&Users{h}, opts...))
}

type usersHandler struct {
	UsersHandler
}

func (h *usersHandler) Create(ctx context.Context, in *User, out *User) error {
	return h.UsersHandler.Create(ctx, in, out)
}

func (h *usersHandler) Get(ctx context.Context, in *GetUserRequest, out *User) error {
	return h.UsersHandler.Get(ctx, in, out)
}

func (h *usersHandler) Mutate(ctx context.Context, in *User, out *User) error {
	return h.UsersHandler.Mutate(ctx, in, out)
}

func (h *usersHandler) Delete(ctx context.Context, in *DeleteUserRequest, out *emptypb.Empty) error {
	return h.UsersHandler.Delete(ctx, in, out)
}
